[project]
name = "pysniff"
version = "1.0"
dependencies = [
    "sarif-om==1.0.4",
    "jschema-to-python==1.2.3",
    "requests==2.32.5",
    "pysniff==1.0",
    "python-dotenv==1.1.1"
]

[project.scripts]
pysniff = "pysniff.main:main"